changes

diff --git a/scripts/open-vins-tuner b/scripts/open-vins-tuner
--- a/scripts/open-vins-tuner
+++ b/scripts/open-vins-tuner
@@ -22,14 +22,26 @@ SIGMA_A_2=(0.00002)
 SIGMA_AB_2=(0.000045)    
 
 ## features - LOCKED IN FOR TRACKING ONLY
-CHI2_MULT=(20)
-SIGMA_PIX=(14)
-SIGMA_PIX_2=(20)
+CHI2_MULT=(15)
+SIGMA_PIX=(4)
+SIGMA_PIX_2=(16)
 
-## feature reps - TRACKING ONLY likes 00, stereo seemed better with 05
-FEAT_REP_MSCKF=(0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5)
-FEAT_REP_SLAM=(0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5)
+## notes, stuff to try
+## 00 tracking, 05 stereo is a known okay setup
+## 02, 03, 14, 15, 30, 35, 54
 
+## feature reps
+FEAT_REP_MSCKF=(0 0 0 0 1 1 3 3 5)
+FEAT_REP_SLAM=(0 2 3 5 4 5 0 5 4)
+
+## cameras
+CAM0_OPT=(true false false true)
+CAM1_OPT=(false true true true)
+
+STEREO_OPT=(false true false true)
+
+## to test:
+# each log with - tracking only, stereo only, binocular stereo, and then multicam
 curr_paramlist=()
 
 ## set most parameters which don't have quotes in json
@@ -48,6 +60,24 @@ set_param () {
     val="${val#\"}"
 
     sed -E -i "/\"$var\":/c\	\"$var\":	$val," ${CONFIG_FILE}
+}
+
+## set most parameters which don't have quotes in json
+set_param_last () {
+    if [ "$#" != "2" ]; then
+        echo "set_param expected 2 args"
+        exit 1
+    fi
+
+    # remove quotes if they exist
+    var=$1
+    var="${var%\"}"
+    var="${var#\"}"
+    val=$2
+    val="${val%\"}"
+    val="${val#\"}"
+
+    sed -E -i "/\"$var\":/c\	\"$var\":	$val" ${CONFIG_FILE}
 }
 
 ## set string parameters which need quotes in json
@@ -74,30 +104,34 @@ set_param_string_last () {
 }
 
 construct_curr_paramlist () {
-    if [ "$#" != "1" ]; then
-        echo "construct_curr_paramlist expected 1 arg"
+    if [ "$#" != "2" ]; then
+        echo "construct_curr_paramlist expected 2 args"
         exit 1
     fi
-    index=$1
+    cam_index=$1
+    param_index=$2
     # clear param list
     curr_paramlist=()
-    # echo ${SIGMA_W[$index]}
-    # curr_paramlist+=(${SIGMA_W[$index]})
-    # curr_paramlist+=(${SIGMA_W_2[$index]})
-    # curr_paramlist+=(${SIGMA_WB[$index]})
-    # curr_paramlist+=(${SIGMA_WB_2[$index]})
-    # curr_paramlist+=(${SIGMA_A[$index]})
-    # curr_paramlist+=(${SIGMA_A_2[$index]})
-    # curr_paramlist+=(${SIGMA_AB[$index]})
-    # curr_paramlist+=(${SIGMA_AB_2[$index]})
+
+    # curr_paramlist+=(${SIGMA_W[$param_index]})
+    # curr_paramlist+=(${SIGMA_W_2[$param_index]})
+    # curr_paramlist+=(${SIGMA_WB[$param_index]})
+    # curr_paramlist+=(${SIGMA_WB_2[$param_index]})
+    # curr_paramlist+=(${SIGMA_A[$param_index]})
+    # curr_paramlist+=(${SIGMA_A_2[$param_index]})
+    # curr_paramlist+=(${SIGMA_AB[$param_index]})
+    # curr_paramlist+=(${SIGMA_AB_2[$param_index]})
 
     # curr_paramlist+=(${CHI2_MULT[0]})
     # curr_paramlist+=(${SIGMA_PIX[0]})
     # curr_paramlist+=(${SIGMA_PIX_2[0]})
-# 
-    curr_paramlist+=(${FEAT_REP_MSCKF[$index]})
-    curr_paramlist+=(${FEAT_REP_SLAM[$index]})
 
+    curr_paramlist+=(${FEAT_REP_MSCKF[$param_index]})
+    curr_paramlist+=(${FEAT_REP_SLAM[$param_index]})
+
+    curr_paramlist+=(${CAM0_OPT[$cam_index]})
+    curr_paramlist+=(${CAM1_OPT[$cam_index]})
+    curr_paramlist+=(${STEREO_OPT[$cam_index]})
 }
 
 set_ov_params_from_list () {
@@ -113,10 +147,16 @@ set_ov_params_from_list () {
     set_param feat_rep_msckf ${curr_paramlist[0]}
     set_param feat_rep_slam ${curr_paramlist[1]}
 
+    set_param cam0_enable ${curr_paramlist[2]}
+    set_param cam1_enable ${curr_paramlist[3]}
+    set_param_last use_stereo ${curr_paramlist[4]}
+
+
+
     # set_param msckf_chi2_multiplier ${curr_paramlist[0]}
     # set_param msckf_sigma_px ${curr_paramlist[1]}
     # # set_param msckf_sigma_px_sq ${curr_paramlist[2]}
-# 
+
     # # set_param slam_chi2_multiplier ${curr_paramlist[0]}
     # set_param slam_sigma_px ${curr_paramlist[1]}
     # set_param slam_sigma_px_sq ${curr_paramlist[2]}
@@ -145,6 +185,8 @@ dirlist_len=${#dirlist[@]}
 # paramlist_len=${#SIGMA_W_2[@]}
 # paramlist_len=${#CHI2_MULT[@]}
 paramlist_len=${#FEAT_REP_SLAM[@]}
+camlist_len=${#CAM0_OPT[@]}
+curr_blowups=0
 
 
 ## also will need "iterations" here, so we can change parameters within the same log
@@ -153,60 +195,81 @@ for (( i=0; i<$dirlist_len; i++ ));
 do
     results_csv="${LOG_DIR}${dirlist[$i]}.csv"
     echo ${results_csv}
-    for (( j=0; j<$paramlist_len; j++ ));
+
+    for (( k=0; k<$camlist_len; k++ ));
     do
-        # construct the list of parameters we are going to test out
-        construct_curr_paramlist $j
-        # need to write into the file a "header" with all ov params in use
-        # echo "sigma_w,sigma_w_2,sigma_wb,sigma_wb_2,sigma_a,sigma_a_2,sigma_ab,sigma_ab_2" >> ${results_csv}
-        # echo "sigma_w,sigma_w_2,sigma_wb,sigma_wb_2,sigma_a,sigma_a_2,sigma_ab,sigma_ab_2,chi2_mult,sigma_pix,sigma_pix_2" >> ${results_csv}
-        
-        # echo "sigma_w,sigma_wb,sigma_a,sigma_ab" >> ${results_csv}
-        # echo "sigma_w_2,sigma_wb_2,sigma_a_2,sigma_ab_2" >> ${results_csv}
-        # echo "chi2,sigma_pix,sigma_pix_2" >> ${results_csv}
-
-        echo "feat_msckf, feat_slam" >> ${results_csv}
-
-
-        printf "%s," "${curr_paramlist[@]}" >> ${results_csv}
-        sed -i '$ s/.$//' ${results_csv}
-        printf "\n" >> ${results_csv}
-
-        # now, actually set those parameters
-        set_ov_params_from_list
-
-        # now, fire up the evaluate-vio process
-        ground_truth="${LOG_DIR}${dirlist[$i]}${GROUND_TRUTH_SUFFIX}"
-        voxl-evaluate-vio -f ${results_csv} -g ${ground_truth} &
-        eval_pid=$!
-
-        sleep 2
-
-        # next, fire up the open vins process
-        voxl-open-vins-server -e ${LOG_DIR}${dirlist[$i]}/ &
-        ov_pid=$!
-
-        sleep 2
-
-
-        # finally, start the log
-        voxl-replay -p ${LOG_DIR}${dirlist[$i]}/ &
-        replay_pid=$!
-
-        sleep 2
-
-        while ps -p $eval_pid > /dev/null
+        for (( j=0; j<$paramlist_len; j++ ));
         do
-            echo "$eval_pid is running"
-            sleep 0.5
+            # construct the list of parameters we are going to test out
+            construct_curr_paramlist $k $j
+            # need to write into the file a "header" with all ov params in use
+            # echo "sigma_w,sigma_w_2,sigma_wb,sigma_wb_2,sigma_a,sigma_a_2,sigma_ab,sigma_ab_2" >> ${results_csv}
+            # echo "sigma_w,sigma_w_2,sigma_wb,sigma_wb_2,sigma_a,sigma_a_2,sigma_ab,sigma_ab_2,chi2_mult,sigma_pix,sigma_pix_2" >> ${results_csv}
+            
+            # echo "sigma_w,sigma_wb,sigma_a,sigma_ab" >> ${results_csv}
+            # echo "sigma_w_2,sigma_wb_2,sigma_a_2,sigma_ab_2" >> ${results_csv}
+            # echo "chi2,sigma_pix,sigma_pix_2" >> ${results_csv}
+
+            echo "feat_msckf, feat_slam, tracking_en, stereo_en, use_stereo" >> ${results_csv}
+
+
+            printf "%s," "${curr_paramlist[@]}" >> ${results_csv}
+            sed -i '$ s/.$//' ${results_csv}
+            printf "\n" >> ${results_csv}
+
+            # now, actually set those parameters
+            set_ov_params_from_list
+
+            # now, fire up the evaluate-vio process
+            ground_truth="${LOG_DIR}${dirlist[$i]}${GROUND_TRUTH_SUFFIX}"
+            voxl-evaluate-vio -f ${results_csv} -g ${ground_truth} &
+            eval_pid=$!
+
+            sleep 2
+
+            # next, fire up the open vins process
+            voxl-open-vins-server -e ${LOG_DIR}${dirlist[$i]}/ &
+            ov_pid=$!
+
+            sleep 2
+
+            # finally, start the log
+            voxl-replay -p ${LOG_DIR}${dirlist[$i]}/ &
+            replay_pid=$!
+
+            sleep 2
+
+            while ps -p $eval_pid > /dev/null
+            do
+                echo "$eval_pid is running"
+                sleep 0.5
+            done
+
+            # need to be able to determine if what we just did was actually good data
+            last_entry=$( tail -n 1  ${results_csv} )
+
+            # easy check: make sure the length is greater than 4, this should catch failures and bad runs
+            # need to also keep track of how many attempts we've had with the same log + params
+            # if > 5? blowups, just give up
+            if [ ${#last_entry} -ge 5 ]; then
+                echo "BLOWUP" >> ${results_csv}
+                curr_blowups=$((curr_blowups+1))
+                if [ ${curr_blowups} -ge 5 ]; then
+                    curr_blowups=0
+                else
+                    j=$((j-1))    # retry with same set of params
+                fi
+            else
+                curr_blowups=0
+            fi
+
+            # once ov_eval process stops, then we're safe to continue onwards in the loop?
+            # kill everything else just in case
+            sudo kill -9 ${replay_pid}
+            sudo kill -9 ${ov_pid}
+            sudo kill -9 ${eval_pid}
+
+            sleep 2
         done
-
-        # once ov_eval process stops, then we're safe to continue onwards in the loop?
-        # kill everything else just in case
-        sudo kill -9 ${replay_pid}
-        sudo kill -9 ${ov_pid}
-        sudo kill -9 ${eval_pid}
-
-        sleep 2
     done
 done
